// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tutorial_Api.DAL;

namespace Tutorial_Api.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("Tutorial_Api.Models.Visitas", b =>
                {
                    b.Property<int>("VisitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.HasKey("VisitaId");

                    b.ToTable("Visitas");

                    b.HasData(
                        new
                        {
                            VisitaId = 1,
                            Fecha = new DateTime(2020, 10, 21, 20, 3, 31, 842, DateTimeKind.Local).AddTicks(8930),
                            Nombres = "Miguel Jose"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
